// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyjauqjduzbbwjmenczr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5amF1cWpkdXpiYndqbWVuY3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NTgwMzUsImV4cCI6MjA3NTUzNDAzNX0.Pu-9ugX40u-SNT641bF9fQrCTgbxBtP_hHCv_jTcjoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});